export const PAGE_SIZE = 10;

export const DUO_CHAMPIOSHIPS = ['COPA POLAR', 'COPA DOUGLAS'];
export type MatchPhase =
  | 'GROUP_STAGE'
  | 'ROUND_OF_16'
  | 'UPPER_BRACKET_QUARTER_FINALS'
  | 'UPPER_BRACKET_SEMIFINALS'
  | 'UPPER_BRACKET_FINALS'
  | 'LOWER_BRACKET_QUARTER_FINALS'
  | 'LOWER_BRACKET_SEMIFINALS'
  | 'LOWER_BRACKET_FINALS'
  | 'QUARTER_FINALS'
  | 'SEMIFINALS'
  | 'THIRD_PLACE'
  | 'FINALS';
